image: docker:latest
cache: {}

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  # DOCKER_TLS_CERTDIR: ''
  REPO: $CI_COMMIT_REF_NAME

stages:
  - prepare

before_script:
 - apk add --update --no-cache bash curl wget git jq && apk upgrade
 - git remote set-url --push origin https://oauth2:$DEPLOY_TOKEN@gitlab.dol.telekom.de/mcsps/k8s-releases.git
 - git config --global user.email 'mcsps-dis@telekom.de'
 - git config --global user.name 'Deploy User'

check-release:
  tags:
    - k8s-executor
  stage: prepare
  script:
    -  REPO=rancher
    -  RTAG=$(curl --silent "https://api.github.com/repos/${REPO}/${REPO}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
    -  DESC=$(curl --silent "https://api.github.com/repos/${REPO}/${REPO}/releases/latest" | jq .body)
    -  LTAG=$(git tag | sed 's/${REPO}-//' | tail -1 )
    -  >
       if [[ "$LTAG" != "$RTAG" ]]; then
         if [ ! (git tag | grep ${REPO}-${RTAG}) ]; then
           git tag ${REPO}-${RTAG} 
           git push origin --tags
           echo -en ${DESC} > ${REPO}/${RTAG}.md
           sed -i 's/"//g' ${REPO}/${RTAG}.md
           sed -i 's/\\r//g' ${REPO}/${RTAG}.md
           git add ${REPO}/${RTAG}.md
           git commit -m "add release desc"
           git push origin HEAD:${REPO}
         else
           echo "in the loop"
         fi
       else
         echo "Nothing to do ${REPO}"
       fi
  except: 
    - tags
