image: mtr.devops.telekom.de/mcsps/mcsps-tools:latest
# image: docker:latest
cache: {}

# beware of the rate limits
# https://developer.github.com/v3/#rate-limiting
# anonymous: 60 per hour
# registered: 5000 per hour

before_script:
 - apk add --update --no-cache findutils bash curl wget git jq openssh-client && apk upgrade
 - mkdir -p ~/.ssh/
 - ssh-keyscan github.com >> ~/.ssh/known_hosts
 - chmod 644 ~/.ssh/known_hosts
 - eval $(ssh-agent -s)
 - echo "$GITHUB_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
 - git config --global user.email 'mcsps-dis@telekom.de'
 - git config --global user.name 'Deploy User'
 
variables:
  BRANCH: $CI_COMMIT_REF_NAME
  # GITHUB_OAUTH: OAuth token to access Github API
  # DEPLOY_TOKEN: Deploy token for Github
  # GITHUB_USER: Github m2m user
  # GITHUB_PASSWORD: Github m2m password
  # GITHUB_SSH_PRIVATE_KEY: Github m2m ssh private key

stages:
  - fetchreleasenote
  - publishgithub

check-release:
  tags:
    - k8s-executor
  stage: fetchreleasenote
  script:
    -  ci/fetchrelease.sh
  except: 
    - tags
    - pipelines

publish-github:
  tags:
    - k8s-executor
  stage: publishgithub
  script:
    -  ci/publishgithub.sh
  except: 
    - tags
